# Generated by Django 2.1.3 on 2018-11-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20181115_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tiporesidencia',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='persona',
            name='ordenar_por_nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
