# Generated by Django 2.1.3 on 2018-11-28 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_auto_20181127_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha', models.IntegerField(null=True)),
                ('actividad', models.TextField(blank=True)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
        ),
    ]
