# Generated by Django 2.1.3 on 2018-11-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.IntegerField(blank=True, null=True)),
                ('fecha_final', models.IntegerField(blank=True, null=True)),
                ('lugar_nacimiento', models.NullBooleanField()),
                ('lugar_defuncion', models.NullBooleanField()),
                ('notas', models.TextField(blank=True)),
                ('localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Localidad')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TipoResidencia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=765)),
                ('temporal', models.NullBooleanField()),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='residencia',
            name='tipo_residencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.TipoResidencia'),
        ),
    ]
