# Generated by Django 2.1.3 on 2018-11-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnTerritorio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaCoordenadas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_corto', models.CharField(max_length=150)),
                ('nombre_largo', models.CharField(blank=True, max_length=765)),
                ('notas', models.TextField(blank=True)),
                ('referencia', models.CharField(blank=True, max_length=765)),
            ],
        ),
        migrations.CreateModel(
            name='Territorio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='sistema_coordenadas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.SistemaCoordenadas'),
        ),
        migrations.AddField(
            model_name='enterritorio',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Localidad'),
        ),
        migrations.AddField(
            model_name='enterritorio',
            name='territorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Territorio'),
        ),
    ]
