# Generated by Django 2.1.3 on 2018-11-28 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0007_auto_20181128_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='tipo_localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.TipoLocalidad'),
        ),
    ]
