# Generated by Django 2.1.3 on 2018-11-28 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0005_auto_20181126_0944'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='jurisdiccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Jurisdiccion'),
        ),
    ]
