# Generated by Django 2.1.3 on 2018-11-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20181127_2028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['fecha_inicio']},
        ),
    ]
