# Generated by Django 2.1.3 on 2018-12-01 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0008_auto_20181128_1528'),
        ('personas', '0007_auto_20181128_1420'),
        ('actividades', '0005_auto_20181128_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.IntegerField(blank=True, null=True)),
                ('fecha_final', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('fecha_inicio', models.IntegerField(blank=True, null=True)),
                ('fecha_final', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('localidad_sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Localidad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAsignacion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInstitucion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TituloAsignacion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('notas', models.TextField(blank=True)),
                ('tipo_asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.TipoAsignacion')),
            ],
        ),
        migrations.AddField(
            model_name='institucion',
            name='tipo_institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.TipoInstitucion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.TituloAsignacion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.Institucion'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Persona'),
        ),
    ]
