# Generated by Django 2.1.3 on 2018-11-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lugares', '0001_initial'),
        ('personas', '0002_auto_20181115_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.IntegerField(blank=True, null=True)),
                ('fecha_final', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Localidad')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TituloCargo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('notas', models.TextField(blank=True)),
                ('tipo_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.TipoCargo')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='titulo_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.TituloCargo'),
        ),
    ]
