# Generated by Django 2.1.3 on 2018-11-22 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnJurisdiccion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='enterritorio',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='enterritorio',
            name='territorio',
        ),
        migrations.RenameModel(
            old_name='Territorio',
            new_name='Jurisdiccion',
        ),
        migrations.DeleteModel(
            name='EnTerritorio',
        ),
        migrations.AddField(
            model_name='enjurisdiccion',
            name='jurisdiccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Jurisdiccion'),
        ),
        migrations.AddField(
            model_name='enjurisdiccion',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Localidad'),
        ),
    ]
