# Generated by Django 2.1.3 on 2018-11-22 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_auto_20181122_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnProvincia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.IntegerField(blank=True, null=True)),
                ('fecha_final', models.IntegerField(blank=True, null=True)),
                ('jurisdiccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Jurisdiccion')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='enprovincia',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Provincia'),
        ),
    ]
