# Generated by Django 2.1.3 on 2018-11-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0003_auto_20181122_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnAudiencia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('jurisdiccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Jurisdiccion')),
                ('provincia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lugares.Provincia')),
            ],
        ),
    ]
