# Generated by Django 2.1.3 on 2018-11-27 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20181117_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.IntegerField(blank=True, null=True)),
                ('fecha_final', models.IntegerField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('persona_id_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_1', to='personas.Persona')),
                ('persona_id_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persona_2', to='personas.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRelacion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=765)),
                ('notas', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='relacion',
            name='tipo_relacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.TipoRelacion'),
        ),
    ]
