# Generated by Django 5.1.3 on 2025-04-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_auto_20181128_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='lugar_defuncion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='lugar_nacimiento',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tiporesidencia',
            name='temporal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
